# Generated by Django 5.1.14 on 2025-11-08 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('amare', 'Amare Teklay'), ('adapticus', 'Homo Adapticus')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('amare', 'Amare Teklay'), ('adapticus', 'Homo Adapticus')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.category')),
            ],
            options={
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
