# Generated by Django 5.1.14 on 2025-11-08 09:42

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('amare', 'Amare Teklay'), ('adapticus', 'Homo Adapticus')], max_length=16)),
                ('slug', models.SlugField(max_length=160)),
                ('is_home', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
            ],
            options={
                'unique_together': {('site', 'slug')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('amare', 'Amare Teklay'), ('adapticus', 'Homo Adapticus')], max_length=16)),
                ('slug', models.SlugField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unlisted', models.BooleanField(default=False)),
                ('reading_time_min', models.PositiveSmallIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='core.author')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='taxonomy.category')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='taxonomy.tag')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('site', 'slug')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('body_md', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_desc', models.CharField(blank=True, max_length=160)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.page')),
            ],
            options={
                'verbose_name': 'page Translation',
                'db_table': 'content_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=350)),
                ('body_md', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_desc', models.CharField(blank=True, max_length=160)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.post')),
            ],
            options={
                'verbose_name': 'post Translation',
                'db_table': 'content_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
